// eslint-disable-next-line import/prefer-default-export
export const PLAYER = {
  GRAASP_PLAYER: 'GRAASP_PLAYER',
  SHOW_CHAT_TOOLTIP: 'SHOW_CHAT_TOOLTIP',
  HIDE_CHAT_TOOLTIP: 'HIDE_CHAT_TOOLTIP',
  SHOW_PINNED_ITEMS_TOOLTIP: 'SHOW_PINNED_ITEMS_TOOLTIP',
  HIDE_PINNED_ITEMS_TOOLTIP: 'HIDE_PINNED_ITEMS_TOOLTIP',
  PINNED_ITEMS: 'PINNED_ITEMS',
  LOAD_MORE: 'LOAD_MORE',
  HIDDEN_WRAPPER_TOOLTIP: 'HIDDEN_WRAPPER_TOOLTIP',
};
